// Generated by https://quicktype.io

export interface MemberInfo {
  members:  Member[];
  metadata: Metadata;
}

export interface Member {
  firstname: string;
  lastname:  string;
  status:    string;
}

export interface Metadata {
  outcome: number;
  status:  number;
  message: string;
}
